language: csharp

env:
  - CONFIGURATION=Release

mono:
  - latest

solution: Dlr.sln

#before_install:
#  - curl https://api.nuget.org/downloads/nuget.exe -o nuget.exe
#  - mono nuget.exe install NUnit
#  - mono nuget.exe install NUnitLite

sudo: required
dist: trusty

dotnet: 2.0.0

script:
  - ls -la /usr/lib/mono/4.5/
  - dotnet restore Dlr.sln --packages ./packages
  - msbuild Build.proj /t:Build "/p:Mono=true;BuildFlavour=$CONFIGURATION"
  - pushd bin/$CONFIGURATION
  - mono ./net40/TestInternalDLR.exe
  - mono ./net45/TestInternalDLR.exe
  - dotnet ./netcoreapp2.0/TestInternalDLR.dll
  - mono ./net40/Metadata.exe
  - mono ./net45/Metadata.exe
  - dotnet ./netcoreapp2.0/Metadata.dll
  - mono ./../../packages/nunit.consolerunner/3.7.0/tools/nunit3-console.exe ./net40/Microsoft.Dynamic.Test.dll
  - mono ./../../packages/nunit.consolerunner/3.7.0/tools/nunit3-console.exe ./net45/Microsoft.Dynamic.Test.dll
  - mono ./../../packages/nunit.consolerunner/3.7.0/tools/nunit3-console.exe ./net40/Microsoft.Scripting.Test.dll
  - mono ./../../packages/nunit.consolerunner/3.7.0/tools/nunit3-console.exe ./net45/Microsoft.Scripting.Test.dll
  - popd

notifications:
  email:
    recipients:
      - developers+int+211+854770831703316759@ironpython.groups.io
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f04e10a7af4b181c18c0
