language: csharp

env:
  - CONFIGURATION=Release

mono:
  - latest

solution: Dlr.sln

before_install:
  - wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell_6.0.1-1.ubuntu.14.04_amd64.deb
  - sudo dpkg -i powershell_6.0.1-1.ubuntu.14.04_amd64.deb

sudo: required
dist: trusty

dotnet: 2.0.0

script:
  - dotnet restore Dlr.sln --packages ./packages
  - pwsh make.ps1 release
  - pwsh make.ps1 test-all

notifications:
  email:
    recipients:
      - developers+int+211+854770831703316759@ironpython.groups.io
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f04e10a7af4b181c18c0
